# Maximum of two numbers in Python

In [1]:
a = 2
b = 4
  
maximum = max(a, b)
print(maximum)

4


In [3]:
a = 2
b = 4
print(max(a, b))

4


In [5]:
def maximum(a, b):
      
    if a >= b:
        return a
    else:
        return b
a = 2
b = 4
print(maximum(a, b))

4


In [7]:
a = -1
b = -4
maximum = max(a,b)
print(maximum)

-1


In [8]:
a = -1
b = -4
print(max(a,b))

-1


In [3]:
def maximum(a, b):
      
    if a >= b:
        return a
    else:
        return b
a = -1
b = -4
print(maximum(a, b))

-1


In [4]:
a = 1 
b = 5 
c = 6
print(max(a,b,c))

6


In [15]:
t1 = -30 
t2 = -34
maximum = max(t1,t2)
print(maximum)

-30


In [16]:
def maximum(a, b):
      
    if a >= b:
        return a
    else:
        return b
a = -67
b = -4
print(maximum(a, b))

-4


In [46]:
def maximum(t1, t2):
      
    if t1 >= t2:
        return t1
    else:
        return t2
t1 = -67
t2 = -4
print(maximum(t1, t2))

-4


# Python program maximum of three numbers

In [20]:
a = 10
b = 14
c = 12
print(max(a, b, c))

14


In [21]:
banana = -32
cherry = -3
mango = -5
print(max( banana, cherry , mango))

-3


In [45]:
def maximum(a, b, c):
  
    if (a >= b) and (a >= c):
        largest = a
  
    elif (b >= a) and (b >= c):
        largest = b
    else:
        largest = c
          
    return largest
   
a = 40
b = 42
c = 26
print(maximum(a, b, c))

42


In [1]:
def maximum(a, b, c):
    
    if (a>=b)and (a>=c):
        laegest = a
        
    elif (b>=a) and (b>=c):
        largest = b
    else:
        largest = c 
        
        return largest
    
a= 20 
b= 30
c= 50
print(maximum(a,b,c))

50


# Python program to print all Prime numbers in an Interval

In [12]:
start = 5
end = 25
  
for i in range(start, end+1):
  if i>1:
    for j in range(2,i):
        if(i % j==0):
            break
    else:
        print(i)

5
7
11
13
17
19
23


In [13]:
num1 = 5 
num2 = 10

for i in range(num1,num2+1):
 if i>1:
        for j in range(3 , i):
            if(i % j==0):
                break
        else :
            print(i)

5
7


In [44]:
start = 11
end = 25
  
for i in range(start, end+1):
  if i>1:
    for j in range(2,i):
        if(i % j==0):
            break
    else:
        print(i)

11
13
17
19
23


# Python program to display all the prime numbers within an interval


In [43]:

lower = 7
upper = 50

print("Prime numbers between", lower, "and", upper, "are:")

for num in range(lower, upper + 1):
   # all prime numbers are greater than 1
   if num > 1:
       for i in range(2, num):
           if (num % i) == 0:
               break
       else:
           print(num)

Prime numbers between 7 and 50 are:
7
11
13
17
19
23
29
31
37
41
43
47


# Program to find the sum of all numbers stored in a list *******


In [4]:
numbers = [6, 5, 3, 8, 4, 2, 5, 4, 11]

sum = 0

for val in numbers:
    sum = sum+val

print("The sum is", sum)

The sum is 48


In [6]:
numbers = [2, 5, 7, 9, 24, 56]

sum = 0 

for val in numbers:
    sum = sum+val
    
print("the sum is " , sum)

the sum is  103


# Python Program for Sum of squares of first n natural numbers
12 + 22 + 32 + 42
= 1 + 4 + 9 + 16
30

In [42]:
def squaresum(n) :

    sm = 0
    for i in range(1, n+1) :
        sm = sm + (i * i)
      
    return sm
  
n = 4
print(squaresum(n))

30


In [11]:
def sqsum(n):

    sm = 0 
    for i in range(1 , n+1):
        sm = sm + (i * i)
        
    return sm 

n = 5 
print(sqsum(n))

55


# to find the largest elements in array 

In [40]:
def largest(arr,n):
  
    # Initialize maximum element
    max = arr[0]
  
    
    for i in range(1, n):
        if arr[i] > max:
            max = arr[i]
    return max
  
# Driver Code
arr = [10, 324, 45, 90, 9808]
n = len(arr)
Ans = largest(arr,n)
print ("Largest in given array is",Ans)

Largest in given array is 9808


# Python Program to find sum of array

In [2]:
def _sum(arr): 
      
    sum=0
      
    for i in arr:
        sum = sum + i
          
    return(sum) 
  
arr = [12, 3, 4, 15] 
   
n = len(arr)   
ans = _sum(arr)   

print ('Sum of the array is ', ans) 

Sum of the array is  34


In [ ]:
 #Python program to print the sum of all elements in an array

In [8]:
arr = [1, 2, 3, 4, 5];     
sum = 0;    
     
#Loop through the array to calculate sum of elements    
for i in range(0, len(arr)):    
   sum = sum + arr[i];    
     
print("Sum of all the elements of an array: " + str(sum));  

Sum of all the elements of an array: 15


# ##Python program to interchange first and last elements in a list

In [1]:
def swapList(newList):
    size = len(newList)
      
    temp = newList[0]
    newList[0] = newList[size - 1]
    newList[size - 1] = temp
      
    return newList
      
newList = [12, 35, 9, 56, 24]
  
print(swapList(newList))

[24, 35, 9, 56, 12]


In [39]:
list = []
n = int(input("Enter the number of elements in list:"))
for x in range(0, n):
    element = input("Enter element:")
    list.append(element)
print("Your current list is:", list)
temp = list[0]
list[0] = list[n-1]
list[n-1] = temp
print("New list is:", list)

Enter the number of elements in list:2
Enter element:3
Enter element:6
Your current list is: ['3', '6']
New list is: ['6', '3']


# Reversing a List in Python

In [4]:
def Reverse(lst):
    return [ele for ele in reversed(lst)]
      
# Driver Code
lst = [10, 11, 12, 13, 14, 15]
print(Reverse(lst))

[15, 14, 13, 12, 11, 10]


In [6]:
systems = ['Windows', 'macOS', 'Linux']
print('Original List:', systems)

systems.reverse()

print('Updated List:', systems)

Original List: ['Windows', 'macOS', 'Linux']
Updated List: ['Linux', 'macOS', 'Windows']


In [ ]:
systems = ['Windows', 'macOS', 'Linux']

# Printing Elements in Reversed Order
for o in reversed(systems):
    print(o)

In [37]:
name_list = ['nupur' , 'mahira' , 'sayli']
for i in reversed(name_list):
    print(i)

sayli
mahira
nupur


In [2]:
a = ['electrical', 'civil','It']
for i in reversed(a):
    print(i)

It
civil
electrical


# Python program to find smallest number in a list

In [14]:
list1 = [10, 20, 4, 45, 99]
 
list1.sort()
print("Smallest element is:", *list1[:1])

Smallest element is: 4


In [24]:
my_list = [2,58,37,4,30]

my_list.sort()
print("smallest element is:" , *my_list[:1])

smallest element is: 2


In [26]:
mynum = [30,50,4,60,1]
min_value = mynum[0]
for i in mynum:
    if min_value > i:
        mim_value = i
print(min_value)

30


In [36]:
thislist = [ 8 , 3, 6, 11]
min_value = thislist[0]
for i in thislist:
    if min_value > i:
        min_value = i
        
print(min_value)

3


# Python program to print even numbers in a list

In [32]:
list1 = [1, 2, 7, 45, 66, 3]
  
for num in list1:

    if num % 2 == 0:
       print(num, end = " ")

2 66 

In [2]:
num1 = [ 1, 4, 7, 9,23]

for num in num1:

    if num % 2 ==0:
        print(num,end =" ")

4 

In [31]:
num1 = [1, 7, 9, 45, 66, 3]
  
for num in num1:

    if num % 2 == 0:
       print(num, end = " ")

66 

In [32]:
num1 = [1, 7 ,9 ,11, 14, 18]

for num in num1:
    
    if num % 2 == 0:
       print(num,end=" ")

14 18 

# Python program to add two Matrices

In [33]:
x = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

result = [[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(x)):
    for j in range(len(y)):
        result[i][j] = x[i][j] + y[i][j]
        
print(result)

[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


In [11]:
x = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
for t in zip(x ,y):
    print(t)

([1, 2, 3], [9, 8, 7])
([4, 5, 6], [6, 5, 4])
([7, 8, 9], [3, 2, 1])


In [8]:
x = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

for t in zip(x , y):
    temp = []
    for x in zip(*t):
        temp.append(sum(x))
    result.append(temp)
print(result)
    
    

[[10, 10, 10], [10, 10, 10], [10, 10, 10], [10, 10, 10], [10, 10, 10], [10, 10, 10]]


In [2]:
x = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

for t in zip(x , y):
    temp = []
    for x in zip(*t):
        temp.append(sum(x))
    result.append(temp)
print(result)

[[10, 10, 10], [10, 10, 10], [10, 10, 10], [10, 10, 10], [10, 10, 10], [10, 10, 10]]


In [3]:
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
  
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
result = [[X[i][j] + Y[i][j]  for j in range
(len(X[0]))] for i in range(len(X))]
  
for r in result:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


# Python program to print even length words in a string

In [47]:
def printWords(s):
      
    # split the string 
    s = s.split(' ') 
      
    # iterate in words of string 
    for word in s: 
          
        # if length is even 
        if len(word)%2==0:
            print(word) 
  
  
# Driver Code 
s = "i am muskan" 
printWords(s) 

am
muskan


In [5]:
def printworld(x):
    x = x.split(' ')
    
    for world in x:
        if len(world)%2 ==0:
            print(world)
            
x = "i am nupur and i love my life"
printworld(x)

am
love
my
life


# Python | Remove all duplicates words from a given sentence

In [60]:
s = "Python is great. and .Java .is also great"
l = s.split(',')
k = []
for i in l:
  
    # If condition is used to store unique string 
    # in another list 'k' 
    if (s.count(i)>1 and (i not in k)or s.count(i)==1):
        k.append(i)
print(' '.join(k))

Python is great. and .Java .is also great


In [61]:
s =  " i love my india, and, i love to my self"
l = s.split(',')
k = []
for i in l :
    if(s. count(i))>1 and (i not in k ) or s.count(i)==1:
        k.append(i)
print(''.join(k))

 i love my india and i love to my self


In [1]:
def unique_list(l):
    temp = []
    for x in l:
        if x not in temp:
            temp.append(x)
    return temp

text_str = ["Python", "Exercises", "Practice", "Solution", "Exercises"]
print("Original String:")
print(text_str)
print("\nAfter removing duplicate words from the said list of strings:")
print(unique_list(text_str))

Original String:
['Python', 'Exercises', 'Practice', 'Solution', 'Exercises']

After removing duplicate words from the said list of strings:
['Python', 'Exercises', 'Practice', 'Solution']


In [15]:
def unique_list(l):
    temp = []
    for x in l:
        if x not in temp:
            temp.append(x)
    return temp
text_str =["maths","english","maths","science"]
print("original string:")
print(text_str)
print("\nafter removing duplicate words from the said list of strings:")
print(unique_list(text_str))


original string:
['maths', 'english', 'maths', 'science']

after removing duplicate words from the said list of strings:
['maths', 'english', 'science']


# Create a Numpy array filled with all zeros | Python

In [36]:
import numpy as np
zero_array = np.zeros(5,int)
print(zero_array)

[0 0 0 0 0]


In [38]:
import numpy as np
zero_array = np.ones([3,3],int)
print(zero_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [39]:
import numpy as np 
zero_array = np.zeros(3,int)
print(zero_array)

[0 0 0]


In [42]:
import numpy as np
zero_array = np.ones([3,2],int)
print(zero_array)

[[1 1]
 [1 1]
 [1 1]]


# Find the most frequent value in a NumPy array

In [43]:
import numpy as np
  
  
# create array
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(x)
  
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


In [45]:
x = np.array([1,2,3,4,5,1,1,])
#output=1

count = np.bincount(x)
print(count)


[0 3 1 1 1 1]


In [46]:
x = np. array([1,2,3,4,5,1,1,1])
count = np.bincount(x)
print(count)
max_value = count[0]
result = 0 
for ind , i in enumerate(count):
    if max_value < i:
        max_value = i
        result = ind
        
print(result)
print(count.argmax())


[0 4 1 1 1 1]
1
1


In [48]:
x = np. array([1,3,5,7,1,2,1,])
count = np.bincount(x)
print(count)
max_value = count[0]
result = 0 
for ind , i in enumerate(count):
    if i > max_value :
        max_value = i 
        result = ind
        
print(result)

[0 3 1 1 0 1 0 1]
1


# Python | Numpy matrix.max()

In [54]:
import numpy as np
          
gfg = np.matrix('[64, 1; 12, 3]')
          
geeks = gfg.max()
    
print(geeks)

64


In [55]:
import numpy as np
          
gfg = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, 9]')
          
geeks = gfg.max()
    
print(geeks)

9


In [3]:
import numpy as np

abc = np.matrix('[2,6,8 ; 4,8,10 ; 11,13,15]')

bca = abc.max()

print(bca)

15


# Python | Numpy matrix.sum()

In [1]:
import numpy as np
             
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
             
# applying matrix.sum() method
geek = gfg.sum()
   
print(geek)

20


In [2]:
import numpy as np 

gfg = np. matrix('[3, 6, 8, 8 9]')
geek = gfg.sum()

print(geek)

34


In [4]:
import numpy as np

a = np.matrix('[3, 6, 7, 9, 23]')
ab = a.sum()

print(ab)

48


In [5]:
import numpy as np 

num1 = np.matrix('[78, 12, 45, 1]')
add_num = num1.sum()

print(add_num)

136


# Replace NumPy array elements that doesn’t satisfy the given condition

In [ ]:
we can use Relational operators like ‘>’, ‘<‘, etc and other functions like numpy.where().

In [6]:
import numpy as np
  
# Creating a 1-D Numpy array
n_arr = np.array([75.42436315, 42.48558583, 60.32924763])
print("Given array:")
print(n_arr)
  
print("\nReplace all elements of array which are greater than 50. to 15.50")
n_arr[n_arr > 50.] = 15.50
  
print("New array :\n")
print(n_arr)

Given array:
[75.42436315 42.48558583 60.32924763]

Replace all elements of array which are greater than 50. to 15.50
New array :

[15.5        42.48558583 15.5       ]


In [17]:
import numpy as np

n_arr = np.array([23, 56 ,78])
print("given array:")
print(n_arr)

print("\nreplace all elements of array which are grater than 20 to 60")
n_arr[n_arr >20] = 60

print("new array :\n")
print(n_arr)

given array:
[23 56 78]

replace all elements of array which are grater than 20 to 60
new array :

[60 60 60]


In [18]:
import numpy as npn_arr
  
# Creating a 2-D Numpy array
import numpy as npn_arr([[45.42436315, 52.48558583, 10.32924763],
                  [5.7439979, 50.58220701, 25.38213418]])
print("Given arn_arrray:")
print(n_arr)
  
print("\nReplace all elements of array which are greater than 30. to 5.25")
n_arr[n_arr > 30.] = 5.25
  
print("New array :\n")
print(n_arr)

Given arn_arrray:
[[45.42436315 52.48558583 10.32924763]
 [ 5.7439979  50.58220701 25.38213418]]

Replace all elements of array which are greater than 30. to 5.25
New array :

[[ 5.25        5.25       10.32924763]
 [ 5.7439979   5.25       25.38213418]]


In [8]:
import numpy as np
  
# Creating a 2-D Numpy array
n_arr = np.array([[45, 52, 10],
                  [1, 5, 25],
                  [50, 40, 81]])
  
print("Given array:")
print(n_arr)
  
print("\nReplace all elements of array which are \
less than or equal to 25 with Nan")
  
print("else with 1 ")
print(np.where(n_arr <= 25, np.nan, 1))

Given array:
[[45 52 10]
 [ 1  5 25]
 [50 40 81]]

Replace all elements of array which are less than or equal to 25 with Nan
else with 1 
[[ 1.  1. nan]
 [nan nan nan]
 [ 1.  1.  1.]]


In [16]:
import numpy as np 

n_arr = np.array([[11, 3 , 23],
                [25, 14,14],
                [15,17,19]])
print("given array:")
print(n_arr)

print("\nreplace all elements of array which are \
less than or equal to 15 with nan")

print("else with 1 ")
print(np.where(n_arr <= 15 ,np.nan , 1))

given array:
[[11  3 23]
 [25 14 14]
 [15 17 19]]

replace all elements of array which are less than or equal to 15 with nan
else with 1 
[[nan nan  1.]
 [ 1. nan nan]
 [nan  1.  1.]]


# Python program to find second largest number in a list

In [19]:
# number in a list
 
# list of numbers
list1 = [10, 20, 4, 45, 99]
 
# sorting the list
list1.sort()
 
# printing the second last element
print("Second largest element is:", list1[-2])

Second largest element is: 45


In [20]:
num1 = [23, 56, 30 ,50 ,60]
num1.sort()
print("second largest elements is :" , num1[-2])

second largest elements is : 56


In [21]:
alist = [ 12, 24, 45, 47, 68, 59]
alist.sort()
print(" third largest eleents is :" , alist[-3])

 third largest eleents is : 47


In [22]:
a = [ 1, 3, 5, 7, 9, 11]
a.sort()
print(" forth largest elements is :" , a[-4])

 forth largest elements is : 5


In [23]:
list1 = [10, 20, 4, 45, 99]
 
# new_list is a set of list1
new_list = set(list1)
 
# removing the largest element from temp list
new_list.remove(max(new_list))
 
# elements in original list are not changed
# print(list1)
 
print(max(new_list))

45


In [25]:
num1 = [1, 3, 5, 7, 9 ,11]
new_num = set(num1)
new_num.remove(max(new_num))
print(max(new_num))

9


In [27]:
a = [ 23, 46, 68, 35, 58, 98,87]
b = set(a)
b.remove(max(b))
print(max(b))

87


# Python program to find smallest number in a list

In [28]:
list1 = [10, 20, 1, 45, 99]
 
 
# printing the maximum element
print("Smallest element is:", min(list1))

Smallest element is: 1


In [29]:
a = [2, 4, 6, 8, 10]
print("smallest elements is :" ,min(a))

smallest elements is : 2


In [30]:
num_list  = [ 34 , 78, 98, 87 , 67, 65 ]
print("smallest elements is ;" , min(num_list))

smallest elements is ; 34


In [31]:
list1 = [10, 20, 4, 45, 99]
 
# sorting the list
list1.sort()
 
# printing the first element
print("Smallest element is:", *list1[:1])

Smallest element is: 4


In [32]:
a = [12, 24, 36, 48 , 60, 72]
a.sort()
print("smallest elements is ;", *a[:1])

smallest elements is ; 12


In [33]:
a = [ 1, 3, 5, 8]
a.sort()
print("smallest elements is;" , *a[:2]) 

smallest elements is; 1 3


# Python Program for cube sum of first n natural numbers

In [35]:
def sumOfSeries(n):
    sum = 0
    for i in range(1, n+1):
        sum +=i*i*i
          
    return sum
  
   
# Driver Function
n = 5
print(sumOfSeries(n))

225


In [38]:
def sumOfSeries(n):
    x = (n * (n + 1)  / 2)
    return (int)(x * x)
  
  
   
# Driver Function
n = 5
print(sumOfSeries(n))

225


In [40]:
def sumofseries(n):
    a = (n * (n+1) / 2 )
    return (int)(a*a)
    
n = 9 
print(sumofseries(n))

2025


In [2]:
def sumofs(n):
    a = (n * (n+1) / 2)
    return (int)(a *a)

n= 7
print(sumofs(n))

784


# Python | Cloning or Copying a list

In [1]:
def Cloning(li1):
    li_copy = li1[:]
    return li_copy
  
# Driver Code
li1 = [4, 8, 2, 0, 15, 18]
li2 = Cloning(li1)
print("Original List:", li1)
print("After Cloning:", li2)

Original List: [4, 8, 2, 0, 15, 18]
After Cloning: [4, 8, 2, 0, 15, 18]


In [5]:
def cloning(num1):
    copy = num1[:]
    return copy 

num1 = [5,7,9,11,13]
num2 = cloning(num1)
print(" original num :" , num1)
print(" after cloning:" , num2)

 original num : [5, 7, 9, 11, 13]
 after cloning: [5, 7, 9, 11, 13]


In [8]:
def cloning(a):
    copy = a[:]
    return copy

a = [2, 4, 8, 16, 32, 64,128]
b = cloning(a)
print(" original num:" , a)
print(" after cloning:" , b)

 original num: [2, 4, 8, 16, 32, 64, 128]
 after cloning: [2, 4, 8, 16, 32, 64, 128]


# Python program to print all odd numbers in a range

In [1]:
start, end = 4, 19
  
# iterating each number in list
for num in range(start, end + 1):
      
    # checking condition
    if num % 2 != 0:
        print(num, end = " ")

5 7 9 11 13 15 17 19 

In [4]:
start , end = 4 ,29

for num in range(start , end + 1) :
    
    if num % 2 != 0 :
        print(num , end = " ")

5 7 9 11 13 15 17 19 21 23 25 27 29 

# Python program to print odd numbers in a List

In [3]:
list1 = [10, 21, 4, 45, 66, 93]
  
# iterating each number in list
for num in list1:
      
    # checking condition
    if num % 2 != 0:
       print(num, end = " ")

21 45 93 

In [1]:
list_a = [1,3,5,7,8,10]

for num in list_a:
    
    if num % 2 != 0:
        print(num, end = " ")


1 3 5 7 

In [2]:
a = [ 3,5,7,11,22,12,14,]

for num in a:
    if num % 2 != 0:
        print(num , end = " ")

3 5 7 11 

In [3]:
series = [57 , 23, 25 ,24 ,1 , 9, 3]
for num in series :
    if num % 2 != 0 :
        print(num , end = ' ')

57 23 25 1 9 3 